# Generated by Django 5.0.6 on 2024-06-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(default=''),
        ),
    ]
