# Generated by Django 5.0.6 on 2024-06-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0004_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
