# Generated by Django 5.0.6 on 2024-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0005_remove_producto_plan_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='plan'),
        ),
    ]
